### PR TITLE
Add custom pageview property support

### PR DESCRIPTION
**Pull request by dgrebb**
I had the idea to implement [custom pageview properties](https://plausible.io/docs/custom-pageview-props#3-filter-your-dashboard-by-custom-properties) on a navigation/routing system for a personal project. This change adds:

1. Load the specific subset of Plausible `script` via `<PlausibleAnalytics />` prop
2. `setAttribute`s on the `<script>` tag via `pageviewprops={{"some-tracking-key": "some value"}}` and [Svelte's `use` action](https://css-tricks.com/using-custom-elements-in-svelte/#aa-using-a-svelte-action-to-force-setting-attributes).

Brief demo:

<details>
<summary><h3 style="display: inline;">Expand Animated Demo</summary>

</details>

Happy to discuss a better implementation! Cheers.

### CODE REVIEW

**Comment by dgrebb** [comment]
Though this works, there are some `type` errors and databinding issues moving between routes. Will update this in a day or so.

- [x] fix typing errors
- [x] update documentation

**Comment by accuser** [comment]
This looks really nice!

**Comment by accuser** [comment]
@dgrebb I want to get this merged - but can we get onto the `develop` branch first? i.e., the `develop` branch needs to be caught up with main (#15).

**Comment by dgrebb** [comment]
@accuser yes — I'll open this back up, rebase, and check its health. Getting a fresh look could bring improvements as well. 

Thanks for bringing this back to the top!

**Comment by dgrebb** [comment]
@accuser this is good to go — I tested everything again locally via `file: /Users/...` install.

No idea why I didn't camelCase `pageviewprops` previously. Docs and code are updated to reflect `pageviewProps` as the component property.

Please let me know if you have any changes or feedback :)

**Comment by accuser** [comment]
The limits that Plausible apply (<= 30 events, <= 2000 characters for values) - do you think that there is any value in providing a check (maybe in `dev` mode) if these are exceeded? Both are easy to measure, but one has greater cost than the other.

**Pull request closed without merging**
