### PR TITLE
Updates devDependencies and peerDependencies

### LINKED ISSUE #4: SvelteKit vulnerable to Cross-Site Request Forgery
CSRF vulnerability in `@sveltejs/kit` <= 1.15.0

- https://github.com/advisories/GHSA-5p75-vc5g-8rv2
- https://github.com/sveltejs/kit/commit/bb2253d51d00aba2e4353952d4fb0dcde6c77123

### PR DESCRIPTION
**Pull request by dgrebb**
Closes #4 and #5

- [x] built and installed locally
- [x] tested in STG
- [x] plausible reports traffic

### CODE REVIEW

**Comment by dgrebb** [comment]
Not sure if this should be rewritten based off of `develop`. Happy to change the base branch!

**Comment by fredrikelmegren** [comment]
Ping @accuser (just in case this PR didn't give you a notification either, as #2)

**Comment by accuser** [comment]
> Not sure if this should be rewritten based off of `develop`. Happy to change the base branch!

Have updated to marge into `develop`.

**Comment by accuser** [comment]
Thanks @dgrebb - have updated the Contributors too. :-)

**Pull request merged**
